# Generated by Django 2.0.6 on 2020-04-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_post_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='post_img/0af17093eea35983de4ff1fe6bf41a40.jpg', upload_to='post_img/'),
        ),
    ]
