# Generated by Django 2.0.6 on 2020-04-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20200410_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='post_img/لوجو_الفريق.png', upload_to='post_img/'),
        ),
    ]
