# Generated by Django 2.0.6 on 2020-04-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_auto_20200411_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.IntegerField(default=' '),
        ),
    ]
